/**
 * Outward-facing semantic error codes the server returns to frontends.
 * Forward-compat mappings for license/concurrency overlay signals that the
 * closed-source app may return (402/429). Per docs/sdk-contract.md §5 these
 * will not fire against the current live dev services, but the mapping exists
 * and is unit-testable with mocks.
 */
export enum ErrorCode {
  VALIDATION_ERROR = 'VALIDATION_ERROR',
  UNAUTHORIZED = 'UNAUTHORIZED',
  FORBIDDEN = 'FORBIDDEN',
  NOT_FOUND = 'NOT_FOUND',
  CONFLICT = 'CONFLICT',
  LICENSE_EXPIRED = 'LICENSE_EXPIRED',
  LICENSE_INVALID = 'LICENSE_INVALID',
  LICENSE_MISSING = 'LICENSE_MISSING',
  CONCURRENCY_LIMIT = 'CONCURRENCY_LIMIT',
  UPSTREAM_ERROR = 'UPSTREAM_ERROR',
  INTERNAL_ERROR = 'INTERNAL_ERROR',
  BAD_REQUEST = 'BAD_REQUEST',
  INVALID_ARGUMENT = 'INVALID_ARGUMENT',
  INVALID_JSON = 'INVALID_JSON',
  CONFLICTING_ARGUMENTS = 'CONFLICTING_ARGUMENTS',
  INVALID_REQUEST = 'INVALID_REQUEST',
  INVALID_FILE_TYPE = 'INVALID_FILE_TYPE',
  FILE_REQUIRED = 'FILE_REQUIRED',
  FILE_COUNT_MISMATCH = 'FILE_COUNT_MISMATCH',
  FILE_TOO_LARGE = 'FILE_TOO_LARGE',
  PAGE_LIMIT_EXCEEDED = 'PAGE_LIMIT_EXCEEDED',
  INVALID_OUTPUT_FILE_NAME = 'INVALID_OUTPUT_FILE_NAME',
  INVALID_PAGE_RANGE = 'INVALID_PAGE_RANGE',
  INVALID_PAGE_INDEX = 'INVALID_PAGE_INDEX',
  INVALID_RECT = 'INVALID_RECT',
  INVALID_QUAD_RECTS = 'INVALID_QUAD_RECTS',
  PAGE_RANGE_EMPTY = 'PAGE_RANGE_EMPTY',
  PASSWORD_REQUIRED = 'PASSWORD_REQUIRED',
  INVALID_PASSWORD = 'INVALID_PASSWORD',
  CERTIFICATE_INVALID = 'CERTIFICATE_INVALID',
  CERTIFICATE_PASSWORD_REQUIRED = 'CERTIFICATE_PASSWORD_REQUIRED',
  CERTIFICATE_PASSWORD_INVALID = 'CERTIFICATE_PASSWORD_INVALID',
  TRUSTED_CERTIFICATE_INVALID = 'TRUSTED_CERTIFICATE_INVALID',
  INVALID_TOKEN = 'INVALID_TOKEN',
  INVALID_STATE = 'INVALID_STATE',
  UNSUPPORTED_OPERATION = 'UNSUPPORTED_OPERATION',
  UNSUPPORTED_ENUM_VALUE = 'UNSUPPORTED_ENUM_VALUE',
  SIGNATURE_NOT_FOUND = 'SIGNATURE_NOT_FOUND',
  WATERMARK_NOT_FOUND = 'WATERMARK_NOT_FOUND',
  BACKGROUND_NOT_FOUND = 'BACKGROUND_NOT_FOUND',
  HEADER_FOOTER_NOT_FOUND = 'HEADER_FOOTER_NOT_FOUND',
  BATES_NOT_FOUND = 'BATES_NOT_FOUND',
  REDACTION_NOT_FOUND = 'REDACTION_NOT_FOUND',
  NO_CHANGES_DETECTED = 'NO_CHANGES_DETECTED',
  CONVERT_FAILED = 'CONVERT_FAILED',
  PDF_PASSWORD_ERROR = 'PDF_PASSWORD_ERROR',
  PDF_FORMAT_ERROR = 'PDF_FORMAT_ERROR',
  PDF_SECURITY_ERROR = 'PDF_SECURITY_ERROR',
  OCR_FAILURE = 'OCR_FAILURE',
  JOB_TIMEOUT = 'JOB_TIMEOUT',
  NO_TABLE = 'NO_TABLE',
  OUT_OF_MEMORY = 'OUT_OF_MEMORY',
  SDK_FILE_ERROR = 'SDK_FILE_ERROR',
  IMAGE_INVALID = 'IMAGE_INVALID',
  SDK_PROCESS_FAILED = 'SDK_PROCESS_FAILED',
  TEMP_FILE_WRITE_FAILED = 'TEMP_FILE_WRITE_FAILED',
  TEMP_FILE_READ_FAILED = 'TEMP_FILE_READ_FAILED',
  RESULT_PACKAGE_FAILED = 'RESULT_PACKAGE_FAILED',
  RESOURCE_EXHAUSTED = 'RESOURCE_EXHAUSTED',
  REQUEST_TIMEOUT = 'REQUEST_TIMEOUT',
  ICC_PROFILE_REQUIRED = 'ICC_PROFILE_REQUIRED',
  ICC_PROFILE_INVALID = 'ICC_PROFILE_INVALID',
}

const BIZ_CODE_TO_ERROR_CODE: Readonly<Record<number, string>> = {
  100001: ErrorCode.INVALID_REQUEST,
  100002: ErrorCode.INVALID_JSON,
  100003: ErrorCode.CONFLICTING_ARGUMENTS,
  100101: ErrorCode.INVALID_FILE_TYPE,
  100102: ErrorCode.FILE_REQUIRED,
  100103: ErrorCode.FILE_COUNT_MISMATCH,
  100104: ErrorCode.FILE_TOO_LARGE,
  100105: ErrorCode.PAGE_LIMIT_EXCEEDED,
  100106: ErrorCode.INVALID_OUTPUT_FILE_NAME,
  110001: ErrorCode.INVALID_PAGE_RANGE,
  110002: ErrorCode.INVALID_PAGE_INDEX,
  110003: ErrorCode.INVALID_RECT,
  110004: ErrorCode.INVALID_QUAD_RECTS,
  110005: ErrorCode.PAGE_RANGE_EMPTY,
  120001: 'AUTH_REQUIRED',
  120002: ErrorCode.INVALID_TOKEN,
  130001: ErrorCode.NOT_FOUND,
  130002: 'JOB_NOT_READY',
  130003: ErrorCode.INVALID_STATE,
  130004: 'IDEMPOTENCY_IN_PROGRESS',
  190001: ErrorCode.CONVERT_FAILED,
  190002: ErrorCode.PDF_PASSWORD_ERROR,
  190003: ErrorCode.PDF_FORMAT_ERROR,
  190004: ErrorCode.PDF_SECURITY_ERROR,
  190005: ErrorCode.OCR_FAILURE,
  190006: ErrorCode.JOB_TIMEOUT,
  190007: ErrorCode.NO_TABLE,
  190008: ErrorCode.OUT_OF_MEMORY,
  190009: ErrorCode.SDK_FILE_ERROR,
  190010: ErrorCode.IMAGE_INVALID,
  190999: ErrorCode.UPSTREAM_ERROR,
};

const PDF_BIZ_CODE_TO_ERROR_CODE: Readonly<Record<number, string>> = {
  100001: ErrorCode.INVALID_ARGUMENT,
  100002: ErrorCode.INVALID_JSON,
  100003: ErrorCode.CONFLICTING_ARGUMENTS,
  100101: ErrorCode.INVALID_FILE_TYPE,
  100102: ErrorCode.FILE_REQUIRED,
  100103: ErrorCode.FILE_COUNT_MISMATCH,
  100104: ErrorCode.FILE_TOO_LARGE,
  100105: ErrorCode.PAGE_LIMIT_EXCEEDED,
  100106: ErrorCode.INVALID_OUTPUT_FILE_NAME,
  110001: ErrorCode.INVALID_PAGE_RANGE,
  110002: ErrorCode.INVALID_PAGE_INDEX,
  110003: ErrorCode.INVALID_RECT,
  110004: ErrorCode.INVALID_QUAD_RECTS,
  110005: ErrorCode.PAGE_RANGE_EMPTY,
  120001: ErrorCode.PASSWORD_REQUIRED,
  120002: ErrorCode.INVALID_PASSWORD,
  120101: ErrorCode.CERTIFICATE_INVALID,
  120102: ErrorCode.CERTIFICATE_PASSWORD_REQUIRED,
  120103: ErrorCode.CERTIFICATE_PASSWORD_INVALID,
  120104: ErrorCode.TRUSTED_CERTIFICATE_INVALID,
  120201: ErrorCode.ICC_PROFILE_REQUIRED,
  120202: ErrorCode.ICC_PROFILE_INVALID,
  130001: ErrorCode.UNSUPPORTED_OPERATION,
  130002: ErrorCode.UNSUPPORTED_ENUM_VALUE,
  130101: ErrorCode.SIGNATURE_NOT_FOUND,
  130102: ErrorCode.WATERMARK_NOT_FOUND,
  130103: ErrorCode.BACKGROUND_NOT_FOUND,
  130104: ErrorCode.HEADER_FOOTER_NOT_FOUND,
  130105: ErrorCode.BATES_NOT_FOUND,
  130106: ErrorCode.REDACTION_NOT_FOUND,
  130107: ErrorCode.NO_CHANGES_DETECTED,
  130011: ErrorCode.LICENSE_EXPIRED,
  130012: 'CONCURRENCY_EXCEEDED',
  190001: ErrorCode.SDK_PROCESS_FAILED,
  190002: ErrorCode.TEMP_FILE_WRITE_FAILED,
  190003: ErrorCode.TEMP_FILE_READ_FAILED,
  190004: ErrorCode.RESULT_PACKAGE_FAILED,
  190005: ErrorCode.RESOURCE_EXHAUSTED,
  190006: ErrorCode.REQUEST_TIMEOUT,
  190999: ErrorCode.INTERNAL_ERROR,
};

export function semanticErrorCodeForBizCode(code: number, source: 'pdf' | 'conversion' | 'unknown' = 'unknown'): string | undefined {
  if (!Number.isFinite(code)) return undefined;
  if (source !== 'unknown') {
    const documented = processingErrorDefinition(source, code)?.errorCode;
    if (documented) return documented;
  }
  if (source === 'pdf') return PDF_BIZ_CODE_TO_ERROR_CODE[code] ?? BIZ_CODE_TO_ERROR_CODE[code];
  return BIZ_CODE_TO_ERROR_CODE[code] ?? PDF_BIZ_CODE_TO_ERROR_CODE[code];
}

const SERVER_ERROR_CODE_TO_NUMERIC: Readonly<Record<string, number>> = {
  [ErrorCode.BAD_REQUEST]: 100001,
  [ErrorCode.VALIDATION_ERROR]: 100001,
  [ErrorCode.INVALID_REQUEST]: 100001,
  [ErrorCode.INVALID_ARGUMENT]: 100001,
  [ErrorCode.INVALID_JSON]: 100002,
  [ErrorCode.CONFLICTING_ARGUMENTS]: 100003,
  [ErrorCode.INVALID_PAGE_RANGE]: 110001,
  [ErrorCode.FILE_TOO_LARGE]: 100104,
  [ErrorCode.REQUEST_TIMEOUT]: 190006,
  [ErrorCode.UNAUTHORIZED]: 140001,
  AUTH_REQUIRED: 140001,
  [ErrorCode.FORBIDDEN]: 140002,
  [ErrorCode.INVALID_TOKEN]: 140002,
  [ErrorCode.NOT_FOUND]: 150001,
  TASK_NOT_READY: 150002,
  [ErrorCode.CONFLICT]: 150003,
  [ErrorCode.INVALID_STATE]: 150003,
  [ErrorCode.LICENSE_EXPIRED]: 130011,
  [ErrorCode.LICENSE_INVALID]: 130011,
  [ErrorCode.LICENSE_MISSING]: 130011,
  [ErrorCode.CONCURRENCY_LIMIT]: 130012,
  CONCURRENCY_EXCEEDED: 130012,
  [ErrorCode.UPSTREAM_ERROR]: 190999,
  [ErrorCode.INTERNAL_ERROR]: 190999,
};

export function numericCodeForServerError(errorCode: string, status: number): number {
  return SERVER_ERROR_CODE_TO_NUMERIC[errorCode] ?? numericCodeForHttpStatus(status);
}

function numericCodeForHttpStatus(status: number): number {
  switch (status) {
    case 400: return 100001;
    case 401: return 140001;
    case 403: return 140002;
    case 404: return 150001;
    case 409: return 150003;
    case 408:
    case 504: return 190006;
    case 413: return 100104;
    case 429: return 130012;
    default: return 190999;
  }
}
import { processingErrorDefinition } from './processing-error-catalog';
